#file: noinspection YAMLSchemaValidation
spring:
  config:
    import: "file:.env[.properties]"
  application:
    name: VaultGuard

  # Database Config
  datasource:
    url: jdbc:h2:mem:vaultguard_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      path: /h2-console
      enabled: true

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${KAFKA_GROUP_ID}
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password:

app:
  kafka:
    topic: ${KAFKA_TOPIC}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_ACCESS_TOKEN_EXPIRE_MILLISECONDS}


