name: VaultGuard CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
      - "features/**"
      - "fixes/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # Sets up Docker correctly for Testcontainers
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Limits Java memory so Docker containers have room to breathe
      - name: Build and Test with Maven
        env:
          MAVEN_OPTS: "-Xmx3072m -XX:+UseG1GC"
        run:
          mvn clean install

      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: '**/target/surefire-reports/'
