name: VaultGuard CI

env:
  CI: true
  MAVEN_OPTS: "-Xmx2048m -XX:+UseG1GC"

on:
  push:
    branches:
      - main
      - master
      - "features/**"
      - "fixes/**"
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # verify Docker is installed and running
      - name: Verify Docker Status
        run: docker info

      - name: Build the application
        run: |
          mvn clean install -DskipTests

      - name: run Integration Test Containers
        run: |
          mvn test -Dtest="com.guard.vaultguard.integrationTest.**.*Test"

      - name: Run Unit Tests
        run: |
          mvn test -Dtest="com.guard.vaultguard.unitTest.**.*Test"

      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: '**/target/surefire-reports/'
